version: "3.8"

networks:
  app-tier:
    driver: bridge

services:
  buddymovie-api:
    container_name: buddymovie-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: ${POSTGRES_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    restart: on-failure

  buddymovie-react:
    container_name: buddymovie-react
    image: potacocat/buddymovie-react:latest
    ports:
      - "3000:3000"
    restart: on-failure

  # For dev only
  postgres-database:
    container_name: postgres-database
    image: postgres:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app-tier
    restart: on-failure

  minio:
    container_name: minio
    image: bitnami/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio-root-user
      MINIO_ROOT_PASSWORD: minio-root-password
      MINIO_DEFAULT_BUCKETS: avatars
    networks:
      - app-tier
    restart: on-failure

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ~/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker

  jenkins_agent:
    container_name: jenkins_agent
    image: jenkins/ssh-agent:jdk17
    privileged: true
    user: root
    expose:
      - 22
    environment:
      JENKINS_AGENT_SSH_PUBKEY: $JENKINS_SSH_KEY