apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgres-url: jdbc:postgresql://postgres-service:5432/database
  postgres-db-name: database
  postgres-dialect: org.hibernate.dialect.PostgreSQLDialect